import json
import heapq
import time
import threading
from collections import defaultdict, deque
from typing import Dict, List, Tuple, Any, Set

LSA_MAX_AGE = 3600  # seconds, not strictly enforced in simulation
LSA_FLOOD_DELAY = 0.01  # small delay to simulate network transmit (seconds)

# ------------------ Topology primitives ------------------

class Topology:
    def __init__(self):
        # adjacency: node -> list of (neighbor, cost)
        self.adj: Dict[str, Dict[str, float]] = defaultdict(dict)

    def add_link(self, a: str, b: str, cost: float = 1.0):
        self.adj[a][b] = cost
        self.adj[b][a] = cost

    def remove_link(self, a: str, b: str):
        self.adj[a].pop(b, None)
        self.adj[b].pop(a, None)

    def update_link_cost(self, a: str, b: str, cost: float):
        if b in self.adj[a] or a in self.adj[b]:
            self.adj[a][b] = cost
            self.adj[b][a] = cost
        else:
            self.add_link(a,b,cost)

    def neighbors(self, node: str) -> Dict[str, float]:
        return dict(self.adj.get(node, {}))

    def nodes(self) -> List[str]:
        return list(self.adj.keys())

    @staticmethod
    def from_json(path: str):
        with open(path, 'r') as f:
            data = json.load(f)
        topo = Topology()
        for link in data.get("links", []):
            topo.add_link(link['a'], link['b'], float(link.get('cost', 1.0)))
        # ensure nodes exist even if isolated
        for n in data.get("nodes", []):
            _ = topo.adj.setdefault(n, {})
        return topo

# ------------------ LSA & Flooding ------------------

class LSA:
    """
    Represent a Link State Advertisement generated by a router.
    Fields:
      origin: router id
      seq: sequence number (monotonic per origin)
      links: dict neighbor->cost (advertised neighbors from origin)
      timestamp: creation time
    """
    def __init__(self, origin: str, seq: int, links: Dict[str, float], timestamp: float = None):
        self.origin = origin
        self.seq = seq
        self.links = dict(links)
        self.timestamp = timestamp if timestamp is not None else time.time()

    def key(self) -> Tuple[str,int]:
        return (self.origin, self.seq)

    def __repr__(self):
        return f"LSA(origin={self.origin},seq={self.seq},links={self.links})"

# ------------------ Router ------------------

class Router:
    def __init__(self, name: str, sim: "OSPFSimulator"):
        self.name = name
        self.sim = sim
        self.topology_view: Dict[str, Dict[str, float]] = {}  # built from LSDB
        # LSDB: origin -> latest LSA (by seq)
        self.lsdb: Dict[str, LSA] = {}
        self.lsa_seq = 0
        self.forward_table: Dict[str, Tuple[str,float]] = {}  # dest -> (next_hop, cost)
        # received_lsa_seqs: origin -> highest_seq_seen (for duplicate suppression)
        self.received_lsa_seqs: Dict[str, int] = {}

    def generate_lsa(self):
        """Create an LSA describing local adjacency (neighbors & costs)."""
        local_links = self.sim.topology.neighbors(self.name)
        self.lsa_seq += 1
        lsa = LSA(self.name, self.lsa_seq, local_links)
        # install into our own LSDB and flood to neighbors
        self._install_lsa(lsa)
        self.flood_lsa(lsa)

    def _install_lsa(self, lsa: LSA) -> bool:
        """Install LSA if it's newer than existing; return True if installed."""
        origin = lsa.origin
        prev_seq = self.received_lsa_seqs.get(origin, 0)
        if lsa.seq <= prev_seq:
            return False
        # accept and update
        self.received_lsa_seqs[origin] = lsa.seq
        self.lsdb[origin] = lsa
        return True

    def flood_lsa(self, lsa: LSA):
        """Flood LSA to all neighbors (simulate asynchronous send)."""
        neighbors = list(self.sim.topology.neighbors(self.name).keys())
        for nb in neighbors:
            # schedule deliver after small delay to simulate network
            self.sim.deliver_lsa(from_router=self.name, to_router=nb, lsa=lsa)

    def receive_lsa(self, lsa: LSA, from_router: str):
        """Process incoming LSA; if new, install and flood onwards (except to from_router)."""
        installed = self._install_lsa(lsa)
        if not installed:
            return
        # flood to neighbors except where it came from
        for nb in self.sim.topology.neighbors(self.name).keys():
            if nb == from_router:
                continue
            self.sim.deliver_lsa(from_router=self.name, to_router=nb, lsa=lsa)

    def build_topology_view(self):
        """Build aggregated topology view (graph) from LSDB entries."""
        graph: Dict[str, Dict[str,float]] = defaultdict(dict)
        for origin, lsa in self.lsdb.items():
            for neigh, cost in lsa.links.items():
                graph[origin][neigh] = cost
                graph[neigh][origin] = cost  # ensure symmetry
        # Also include nodes that may have empty adjacency
        for n in self.sim.topology.nodes():
            graph.setdefault(n,{})
        self.topology_view = dict(graph)

    def run_dijkstra(self):
        """From this router, compute shortest path to all nodes based on topology_view."""
        src = self.name
        dist: Dict[str, float] = {n: float('inf') for n in self.topology_view.keys()}
        prev: Dict[str, str] = {}
        dist[src] = 0.0
        pq = [(0.0, src)]
        visited: Set[str] = set()
        while pq:
            d,u = heapq.heappop(pq)
            if u in visited: continue
            visited.add(u)
            for v,cost in self.topology_view.get(u, {}).items():
                nd = d + cost
                if nd < dist.get(v, float('inf')):
                    dist[v] = nd
                    prev[v] = u
                    heapq.heappush(pq,(nd,v))
        # Build forwarding table: next hop for each destination
        fwd = {}
        for dest in self.topology_view.keys():
            if dest == src: continue
            if dist.get(dest,float('inf')) == float('inf'):
                continue
            # reconstruct path to find next hop
            path = []
            node = dest
            while node != src:
                path.append(node)
                node = prev.get(node)
                if node is None:
                    break
            if node is None:
                # no path
                continue
            path.append(src)
            path.reverse()  # src -> ... -> dest
            next_hop = path[1] if len(path) >= 2 else dest
            fwd[dest] = (next_hop, dist[dest])
        self.forward_table = fwd

    def recompute(self):
        """Rebuild topology view and routing table."""
        self.build_topology_view()
        self.run_dijkstra()

    def pretty_print_table(self):
        print(f"Routing table for {self.name}:")
        print(f"{'DEST':<8} {'NEXT_HOP':<8} {'COST':<6}")
        for dest,(nh,cost) in sorted(self.forward_table.items()):
            print(f"{dest:<8} {nh:<8} {cost:<6}")
        print()

# ------------------ Simulator ------------------

class OSPFSimulator:
    def __init__(self, topology: Topology):
        self.topology = topology
        # create routers
        self.routers: Dict[str, Router] = {n: Router(n, self) for n in topology.nodes()}
        # event queue for LSA deliveries (simple synchronous queue)
        self.delivery_queue: deque = deque()

    def start_network(self):
        """Initial LSA generation by all routers (bootstrap)."""
        for r in self.routers.values():
            r.generate_lsa()
        # process queued deliveries until stable
        self.process_delivery_queue()
        # initial recompute
        self.recompute_all()

    def deliver_lsa(self, from_router: str, to_router: str, lsa: LSA):
        """Enqueue an LSA delivery (simulate asynchronous transmit)."""
        # enqueue as (to_router, from_router, lsa)
        self.delivery_queue.append((to_router, from_router, lsa))

    def process_delivery_queue(self):
        """Process queued LSA deliveries until no more new LSAs propagate."""
        # BFS-like processing; each delivery may enqueue new deliveries
        while self.delivery_queue:
            to_router, from_router, lsa = self.delivery_queue.popleft()
            # simulate tiny delay
            time.sleep(LSA_FLOOD_DELAY)
            # deliver
            if to_router not in self.routers:
                continue
            self.routers[to_router].receive_lsa(lsa, from_router)

    def recompute_all(self):
        for r in self.routers.values():
            r.recompute()

    def print_all_tables(self):
        for r in sorted(self.routers.values(), key=lambda x: x.name):
            r.pretty_print_table()

    # user-level helpers
    def send_test_packet(self, src: str, dst: str) -> Tuple[bool, List[str]]:
        """Simulate forwarding using current forward tables. Return (delivered, path)."""
        path = []
        cur = src
        steps = 0
        max_hops = 50
        if src not in self.routers or dst not in self.routers:
            return False, path
        path.append(cur)
        while cur != dst and steps < max_hops:
            rt = self.routers[cur]
            entry = rt.forward_table.get(dst)
            if entry is None:
                return False, path
            next_hop,_ = entry
            path.append(next_hop)
            cur = next_hop
            steps += 1
            if cur == dst:
                return True, path
        return (cur == dst), path

    def update_link_cost(self, a: str, b: str, cost: float):
        """Change physical link, generate new LSAs at endpoints, flood, recompute."""
        print(f"Simulator: updating cost {a}<->{b} to {cost}")
        self.topology.update_link_cost(a,b,cost)
        # endpoints generate new LSAs
        if a in self.routers:
            self.routers[a].generate_lsa()
        if b in self.routers:
            self.routers[b].generate_lsa()
        self.process_delivery_queue()
        self.recompute_all()

    def remove_link(self, a: str, b: str):
        print(f"Simulator: removing link {a}<->{b}")
        self.topology.remove_link(a,b)
        if a in self.routers:
            self.routers[a].generate_lsa()
        if b in self.routers:
            self.routers[b].generate_lsa()
        self.process_delivery_queue()
        self.recompute_all()

# ------------------ Demo / CLI ------------------

def demo_from_file(path: str):
    topo = Topology.from_json(path)
    sim = OSPFSimulator(topo)
    print("Bootstrapping network (initial LSA flood)...")
    sim.start_network()
    print("Initial routing tables (after convergence):\n")
    sim.print_all_tables()

    tests = [("R1","R5"),("R5","R1"),("R1","R3"),("R3","R5")]
    for s,d in tests:
        delivered,path = sim.send_test_packet(s,d)
        print(f"Packet {s}->{d}: delivered={delivered}, path={' -> '.join(path)}")

    # dynamic update: increase R2-R3
    print("\n*** Update: increase cost R2-R3 to 50 (simulate congestion) ***\n")
    sim.update_link_cost("R2","R3",50.0)
    sim.print_all_tables()
    delivered,path = sim.send_test_packet("R1","R5")
    print(f"After update: Packet R1->R5: delivered={delivered}, path={' -> '.join(path)}")

    # dynamic removal
    print("\n*** Remove: link R3-R4 (simulate failure) ***\n")
    sim.remove_link("R3","R4")
    sim.print_all_tables()
    delivered,path = sim.send_test_packet("R3","R5")
    print(f"After removal: Packet R3->R5: delivered={delivered}, path={' -> '.join(path)}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Mini OSPF Simulator")
    parser.add_argument("--topo", default="topology.json", help="Topology JSON file")
    args = parser.parse_args()
    demo_from_file(args.topo)
